### ISSUE TITLE
React Boilerplate

### ISSUE THREAD

**Issue by gabipurcaru** [react-bucharest/hello-world#3]
![](http://cdn.movieweb.com/img.news/NEnBKLdGEGLarq_1_1.jpg)

_Whenever you start a new React project, you need to set up some boilerplate. You can use Yeoman or a starter kit, but chances are it won't be set up just the way you want it. The alternative is that you roll up your sleeves and do it yourself. This is what I'm going to cover_
### Steps:
1. `git init`
2. `npm init`
3. Install webpack `npm install --save webpack`
4. Set up webpack (with live reload, file copy plugin for index.html, dev server)
5. Install babel, and set it up with webpack
6. Install React
7. Create a basic app!

**Comment by gabipurcaru** [comment]
Update: here's an asciinema cast with most of the presentation

https://asciinema.org/a/0y8k12bgj6e8timeje4r1h090

@skidding, @therealthing what do you think?

**Comment by ovidiuch** [comment]
Good stuff! I think this is going to turn into a very educational talk.

@gabipurcaru can you also submit a PR with the final code? We can provide feedback here and there, but most importantly, @therealthing can start working on his code on top of yours (not a lot of days left).

PS. I want to post "What you'll learn during @gabipurcaru's talk" on the Fb group tomorrow. Can you rewrite the steps into more descriptive bullet points like "How to start a npm project", "How to set up webpack", etc.?

Thanks! 👯

**Comment by gabipurcaru** [comment]
Steps:
1. How to start a npm project for frontend code
2. How to set up webpack in order to build your React project
3. How to enable ES6 features with babel
4. How to bundle React (and other libraries) with your code

If I have enough time I can cover:
5. How to compile CSS/LESS/etc. with webpack

**Comment by therealthing** [comment]
Salutare,

Atasez prezentarea mea despre Redux (in format keynote si ppt), care e
aproape gata. Desigur la fiecare slide voi detalia informatiile. Orice
feedback este bine venit si va multumesc in avans.

Ramane sa ma ocup acum un pic de cod, pentru a avea gata si partea
practica. Am gasit un API de la google pentru translate
https://cloud.google.com/translate/v2/quickstart#language_detect pe care
il voi folosi pentru traducerea Hello World-ului.

Numai bine!

**Comment by gabipurcaru** [comment]
@therealthing, nu vad nu ar trebui sa fie prezentarea. Poti sa o mai atasezi odata?

**Comment by ovidiuch** [comment]
@therealthing nici eu nu vad nimic atasat.

**Comment by therealthing** [comment]
[dan-jipa-redux-react.pdf](https://github.com/react-bucharest/hello-world/files/312223/dan-jipa-redux-react.pdf)

**Comment by ovidiuch** [comment]
Thanks. Looking good!

"high level components = smart components" mi se pare cam abstract. Poate
"high level components = components with access to global state"?
